# Generated by Django 3.2.6 on 2021-08-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('imageUri', models.ImageField(upload_to='images/')),
                ('player_jersey_number', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('run', models.IntegerField()),
                ('highest_scores', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketadmin.match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=200)),
                ('logouri', models.ImageField(upload_to='images/')),
                ('club_state', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('players', models.ManyToManyField(related_name='players', to='cricketadmin.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdate', models.DateField(blank=True, null=True)),
                ('score_a', models.IntegerField()),
                ('score_b', models.IntegerField()),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketadmin.match')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='cricketadmin.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='cricketadmin.team')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketadmin.team')),
            ],
        ),
    ]
